//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonkeyFly.MES.Models
{
    using Core;
    using System;
    public class SYS_ControlParameters : IModel
    {
        public int ID { get; set; }
        public string SystemID { get; set; }
        public string ControlParameterID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string DescriptionOne { get; set; }
        public string Key { get; set; }
        public string value { get; set; }
        public int DateType { get; set; }
        public string ParameterTypeID { get; set; }
        public string PageNumber { get; set; }
        public bool IsEnable { get; set; }
        public bool IsDefault { get; set; }
        public bool IsSystem { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string Comments { get; set; }
        public string Modifier { get; set; }
        public System.DateTime ModifiedTime { get; set; }
        public System.DateTime ModifiedLocalTime { get; set; }
        public string Creator { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime CreateLocalTime { get; set; }
    }
}
